AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: junction23 backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analyze/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        Analyze:
          Type: HttpApi
          Properties:
            Path: /analyze
            Method: get
            ApiId: !Ref Api

  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "junction23-storage"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"

  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getSignedURL/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket: !Ref S3UploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3UploadBucket
        - Statement:
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::${S3UploadBucket}/"
              Action:
                - s3:putObjectAcl
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /uploads
            Method: get
            ApiId: !Ref Api

  # TempConversionDepLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: junction23-ffmpeg-layer
  #     Description: ffmpeg dependencies for junction23 python lambda
  #     ContentUri:
  #       Bucket: junction23-ffmpeg
  #       Key: test
  #     CompatibleRuntimes:
  #       - python3.11
  #     LicenseInfo: GPLv3
  #     RetentionPolicy: Retain
