AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: junction23 backend

Globals:
  Function:
    Timeout: 29
    MemorySize: 2048

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  InvokeAnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: invokeAnalyze/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Analyze:
          Type: HttpApi
          Properties:
            Path: /analyze
            Method: get
            ApiId: !Ref Api
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref AnalyzerFunction

  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: junction23-backend-AnalyzerFunction
      CodeUri: analyze/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - arn:aws:lambda:eu-west-1:368093168477:layer:junction23-ffmpeg-layer:4
        - arn:aws:lambda:eu-west-1:368093168477:layer:junction23-opencv-layer:5
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3ResultBucket
        - Statement:
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::${S3ResultBucket}/"
              Action:
                - s3:putObjectAcl

  AnalyzeVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: junction23-backend-AnalyzeVideoFunction
      CodeUri: analyzeVideo/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3ResultBucket
        - Statement:
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::${S3ResultBucket}/"
              Action:
                - s3:putObjectAcl

  S3ResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: junction23-storage-results

  ResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: junction23-backend-ResultFunction
      CodeUri: result/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Analyze:
          Type: HttpApi
          Properties:
            Path: /result
            Method: get
            ApiId: !Ref Api
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3ResultBucket
        - Statement:
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::${S3ResultBucket}/"
              Action:
                - s3:GetObject

  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "junction23-storage"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"

  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getSignedURL/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket: !Ref S3UploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3UploadBucket
        - Statement:
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::${S3UploadBucket}/"
              Action:
                - s3:putObjectAcl
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /uploads
            Method: get
            ApiId: !Ref Api
